apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Mi
  claimRef:
    name: mongo-pv-claim
    namespace: default
  hostPath:
    path: /data
    type: Directory