apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo_pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  claimRef:
    name: mongo_pv_claim
    namespace: default
  hostpath:
    path: /data/db
    type: Directory