---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # naming the deployment

spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service
  
  # Let's create 2 replica sets of this instances/pods
  replicas: 2

  # template to use iy's label for k8 service to launch in the browser
  template:
    metadata:
      labels:
        app: nginx # This label connects to the service or any other
  
  # Let's define the container spec
    spec:
      containers:
      - name: nginx
        image: sachadorf/sre_customised_nginx:latest
        ports:
        - containerPort: 80