---
# Select the type of API version and type of service
apiVersion: v1
kind: Service
# Metadata for name
metadata:

  name: nginx-deployment
  namespace: default

# Specification to include ports Selector to connect
spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 80

# Let's define the selector and label to connect to nginx
  selector:
    app: nginx # this label connects this service to deployment

  # Creating Loadbalancer type of deployment
  type: LoadBalancer